### ISSUE TITLE
Scrape all related civil cases (e.g. Habeas petitions)

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#49]
Habeas petitions are separate cases that are civil in nature, but are related to criminal cases. We'll want details about these cases in order to do some comparisons.

**Comment by lianilychee** [comment]
Validate if still needed and priority with Nick.

**Comment by tpadmanabhan** [comment]
@nicolassaw Nick please review

**Comment by nicolassaw** [comment]
I think we can close this ticket. It's not a necessary inquiry for the
scope of this project.

Based on some of the practice I've seen, habeas petitions can be filed in
the criminal courts and are sometimes used as tools for bond advocacy or to
secure release. For the regular day-to-day case, I would say that evidence
of habeas petitions would be found in the criminal court (County or
District) presiding over the case for bond advocacy, which we are already
scraping. Habeas petitions are also used in capital/death penalty and other
appellate litigation, which is where you see them filed in the civil
context. Because we should focus on non-appellate practice, there is little
reason to go and find civil habeas petition cases.

Nicolas Sawyer

**Comment by tpadmanabhan** [comment]
Closing ticket per Nick's review comment. @nicolassaw advised to focus on non-appellate practice

**Comment by tpadmanabhan** [comment]
@lianilychee Liani, do we have a 'closed' status in addition to 'done'? This ticket won't be worked per @nicolassaw

**Comment by lianilychee** [comment]
Nick recommended that we can close this ticket, since we are only dealing with criminal cases, while this tix is asking abt civil.
